WebsiteApp/urls.py
from django.urls import path
from .views import  inicio, eventos, discografia, biografia, shop
from . import views 



urlpatterns = [
    path('', inicio, name="Inicio"),
    path('eventos/', eventos, name="Eventos"),
    path('discografia/', discografia, name="Discografia"),
    path('biografia/', biografia, name="Biografia"),
    path('shop/', shop, name="Shop"),
    # Formularios
    path('agregarEvento/',views.agregarEvento, name='agregarEvento'),
    path('lista_eventos/',views.lista_eventos, name='lista_eventos'),
    path('agregarDisco/',views.agregarDisco, name='agregarDisco'),
    path('lista_disco/',views.lista_disco, name='lista_disco'),
]

WebsiteProject/urls.py
from django.contrib import admin
from django.urls import path, include
# from WebsiteApp.views import inicio

urlpatterns = [
    path('admin/', admin.site.urls),
    path('websiteapp/', include('WebsiteApp.urls')),
]

WebsiteApp/models.py
from django.db import models

# Create your models here.

class Evento(models.Model):
    fecha = models.DateField()
    lugar = models.CharField(max_length=100)
    pais = models.CharField(max_length=50)
    estado = models.CharField(max_length=50)
    boton_compra = models.URLField(blank=True)

    # def __str__(self):
    #     return f'{self.fecha} - {self.lugar}'python manage.py makemigrations


class Discos(models.Model):
    titulo = models.CharField(max_length=100)
    año_lanzamiento = models.PositiveIntegerField()
    portada = models.ImageField(upload_to='discos/', null=True, blank=True)
    url_compra = models.URLField(blank=True)

    # def __str__(self):
    #     return self.titulo

class Biografia(models.Model):
    nombre = models.CharField(max_length=100)
    instrumento = models.CharField(max_length=50)
    foto = models.ImageField(upload_to='biografia/', null=True, blank=True)

    # def __str__(self):
    #     return self.nombre    


class Shop(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    imagen = models.ImageField(upload_to='shop/', null=True, blank=True)
    categoria = models.CharField(max_length=50)
    disponible = models.BooleanField(default=True)

    # def __str__(self):
    #     return self.nombre

WebsiteApp/forms.py
from django import forms
from .models import Evento, Discos, Shop



# Formulario eventos

class EventoForm(forms.ModelForm):
    class Meta:
        model = Evento
        fields = ['fecha', 'lugar', 'pais', 'estado', 'boton_compra']
             
class DiscosForm(forms.ModelForm):
    class Meta:
        model = Discos
        fields = ['titulo', 'year_lanzamiento', 'portada', 'url_compra']       

class ShopForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = ['nombre', 'descripcion', 'precio', 'imagen', 'categoria', 'disponible']

WebsiteApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest
from .models import Evento, Discos, Shop
from .forms import EventoForm, DiscosForm, ShopForm



# from django.views.generic import ListView
# from django.views.generic.detail import DetailView
# from django.views.generic.edit import DeleteView, UpdateView, CreateView
# from .models import Curso, Profesor
# from .forms import CursoFormulario, ProfesorFormulario

# Create your views here.

# def evento(req, fecha, lugar, pais, estado, boton_compra):

#     evento = Evento(fecha=fecha, lugar=lugar, pais=pais, estado=estado, boton_compra=boton_compra)
#     evento.save()

#     return HttpResponse(f"""
#     <p>Fecha: {evento.fecha} Lugar: {evento.lugar} País: {evento.pais} Estado: {evento.estado}  </p>
#     """)
    
# def listar_eventos(req):
#     lista = Evento.objects.all()
#     return render(req, "lista_eventos.html", {"lista_eventos": lista})


def eventos(req):
    return render(req, "eventos.html")

def inicio(req):
    return render(req, "inicio.html")

def discografia(req): 
    return render(req, "discografia.html")

def biografia(req):
    return render(req, "biografia.html")

def shop(req):
    return render(req, "shop.html")

def lista_eventos(request):
    eventos = Evento.objects.all()  # pylint: disable=no-member
    return render(request, 'lista_eventos.html', {'eventos': eventos})

def lista_disco(request):
    disco = Evento.objects.all()  # pylint: disable=no-member
    return render(request, 'lista_disco.html', {'disco': disco})

# forms

# def agregarEvento(req):

#     print('metho', req.method)
#     print('POST', req.POST)
#     if req.method == 'POST':
#         return render(req, "agregarEvento.html" )
#         pass
#     else:
#         return render(req, "agregarEvento.html" )

# def agregarEvento(req):

#     if req.method == 'POST':
#         # Si la solicitud es POST, procesa los datos del formulario
#         form = EventoForm(req.POST)
#         if form.is_valid():
#             # Si el formulario es válido, guarda el evento en la base de datos
#             form.save()
#             # Redirige a la página de inicio o a donde desees después de guardar
#             return redirect('Inicio')  
#     else:
#         # Si la solicitud no es POST, muestra el formulario en blanco
#         form = EventoForm()
    
#     return render(req, 'agregarEvento.html', {'form': form})




# def agregarEvento(req):
#     if req.method == 'POST':
#         # Si la solicitud es POST, procesa los datos del formulario
#         form = EventoForm(req.POST)
#         if form.is_valid():
#             # Si el formulario es válido, guarda el evento en la base de datos
#             form.save()
#             # Redirige a la página de inicio después de guardar el evento
#             return redirect('inicio')  
#     else:
#         # Si la solicitud no es POST, muestra el formulario en blanco
#         form = EventoForm()
    
#     # Recupera todos los eventos de la base de datos
#     eventos = Evento.objects.all() # pylint: disable=no-member
    
#     # Renderiza el HTML 'lista_eventos' con los eventos
#     return render(req, 'lista_eventos.html', {'eventos': eventos, 'form': form})





def agregarEvento(req):
    if req.method == 'POST':
        # Si la solicitud es POST, procesa los datos del formulario
        form = EventoForm(req.POST)
        if form.is_valid():
            # Si el formulario es válido, guarda el evento en la base de datos
            form.save()
            # Redirige a la página de lista de eventos después de guardar el evento
            return redirect('lista_eventos') 
    else:
        # Si la solicitud no es POST, muestra el formulario en blanco
        form = EventoForm() # pylint: disable=no-member
    
    return render(req, 'agregarEvento.html', {'form': form})



def agregarDisco(req):
    if req.method == 'POST':
        form = DiscosForm(req.POST, req.FILES)
        if form.is_valid():
            form.save()
            return redirect('lista_disco')
    else:
        form = DiscosForm() # pylint: disable=no-member
    
    return render(req, 'agregarDisco.html', {'form': form})




# def crear_producto(request):
#     if req.method == 'POST':
#         form = ShopForm(req.POST, req.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('lista_productos')  
#     else:
#         form = ShopForm() 
    
#     return render(request, 'crear_producto.html', {'form': form})

WebsiteApp/templates/agregarDisco.html
{% extends 'padre.html' %}

{% block contenidoQueCambia %}

    <div class="contenido">
        <h1 class="titulo">Discografias</h1>
        <h2 class="subtitulo">Agregar Disco</h2>

        <br>

        <form action="{% url 'agregarDisco' %}" method="post" enctype="multipart/form-data">{% csrf_token %}          
            <legend>Información del Disco</legend>
           
            <label for="titulo">Título:</label>
            <input type="text" id="titulo" name="lugar" maxlength="100" required placeholder="Ingrese el título del disco">
    
            <label for="anio">Año:</label>
            <input type="text" id="anio" name="pais" maxlength="50" required placeholder="Ingrese el año de lanzamiento">
    
            <label for="imagen">Imagen:</label>
            <input type="file" id="imagen" name="imagen" accept="image/*">
    
            <label for="boton_compra">Botón de Compra (URL):</label>
            <input type="url" id="boton_compra" name="boton_compra" maxlength="200" placeholder="Ingrese la URL de compra (opcional)">
        
            <button type="submit">Guardar</button>
        </form>
        

    </div>

{% endblock contenidoQueCambia %}

WebsiteApp/templates/agregarEvento.html
{% extends 'padre.html' %}

{% block contenidoQueCambia %}

    <div class="contenido">
        <h1 class="titulo">Eventos</h1>
        <h2 class="subtitulo">Agregar nueva fecha</h2>
        <br>


        <form action="{% url 'agregarEvento' %}" method="post">{% csrf_token %}
            
            <label for="id_fecha">Fecha:</label>
            <input type="date" id="id_fecha" name="fecha" required><br>
    
            <label for="id_lugar">Lugar:</label>
            <input type="text" id="id_lugar" name="lugar" maxlength="100" required><br>
    
            <label for="id_pais">País:</label>
            <input type="text" id="id_pais" name="pais" maxlength="50" required><br>
    
            <label for="id_estado">Estado:</label>
            <input type="text" id="id_estado" name="estado" maxlength="50" required><br>
    
            <label for="id_boton_compra">Botón de Compra (URL):</label>
            <input type="url" id="id_boton_compra" name="boton_compra" maxlength="200"><br>
    
            <button type="submit">Guardar</button>
        </form>

    </div>

{% endblock contenidoQueCambia %}

WebsiteApp/templates/biografia.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Biografia</h1>
</body>
</html>

WebsiteApp/templates/discografia.html
{% extends 'padre.html' %}

{% block contenidoQueCambia %}
    <div class="contenido">
        <h1 class="titulo">Discos</h1>
    </div>    




¡

{% endblock contenidoQueCambia %}

WebsiteApp/templates/eventos.html
{% extends 'padre.html' %}

<!-- {% include 'navbar.html' %} -->

{% block contenidoQueCambia %}
    <div class="contenido">
        <h1 class="titulo">Eventos</h1>


    </div>

{% endblock contenidoQueCambia %}

WebsiteApp/templates/inicio.html
{% extends 'padre.html' %}

{% block contenidoQueCambia %}

<section id="banner">
	<header>
		<h2>Hi. You're looking at <strong>Helios</strong>.</h2>
		<p>
			A (free) responsive site template by <a href="http://html5up.net">HTML5 UP</a>.
			Built with HTML5/CSS3 and released under the <a href="http://html5up.net/license">CCA</a> license.
		</p>
	</header>
</section>

{% endblock contenidoQueCambia %}

WebsiteApp/templates/lista_disco.html
{% extends 'padre.html' %}

{% block contenidoQueCambia %}

    <diV class="contenido">
        <h1 class="titulo">Toda la Discografia</h1>
            <ul>
                {% for disco in discos %}
                    <li>{{ discos.titulo }} - {{ discos.year_lanzamiento }} - {{ discos.portada }}</li>
                    <li><a href="{{ evento.boton_compra }}" class="buttonCustom" target="_blank">Comprar boleto</a></li>                    
                {% endfor %}  
            </ul>
    </diV>

   
{% endblock contenidoQueCambia %}

WebsiteApp/templates/lista_eventos.html
{% extends 'padre.html' %}

{% block contenidoQueCambia %}

    <diV class="contenido">
        <h1 class="titulo">Todos los Conciertos</h1>
        <ul>
            {% for evento in eventos %}
                <li>{{ evento.fecha }} - {{ evento.lugar }}  - {{ evento.pais }}  - {{ evento.estado }}</li>
                <li><a href="{{ evento.boton_compra }}" class="buttonCustom" target="_blank">Comprar boleto</a></li>                    
            {% endfor %}  
        </ul>

    </diV>

    
{% endblock contenidoQueCambia %}

WebsiteApp/templates/navbar.html
<nav id="nav">
    <ul>
        <li><a href="{% url 'Inicio' %}">Home</a></li>
        <li><a href="{% url 'lista_disco' %}">Discografía</a></li>
        <li><a href="{% url 'lista_eventos' %}">Eventos</a></li>
        <li><a href="{% url 'Biografia' %}">Biografía</a></li>
    </ul>
</nav>

WebsiteApp/templates/padre.html
<!DOCTYPE HTML>
<!--
	Helios by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		{% load static %}
		<title>Helios by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<link rel="stylesheet" href="{% static 'assets/css/stiles.css' %}" />
		<!-- <noscript><link rel="stylesheet" href="assets/css/noscript.css" /></noscript> -->
	</head>
	<body class="homepage is-preload">
		<div id="page-wrapper">

			<!-- Header -->
				<div id="header">
					<!-- Nav -->
						<nav id="nav">
							<ul>
								<li><a href="/websiteapp/lista_eventos">Conciertos</a></li>
								<li><a href="/websiteapp/lista_disco">Música</a></li>
								<li><a href="/websiteapp/shop">Shop</a></li>
								<botoom><a href="/websiteapp/login"  class="boton-login">Iniciar sesión</a></botoom>
							</ul>
						</nav>
				</div>

			<!-- block -->

            {% block contenidoQueCambia %}

            {% endblock contenidoQueCambia %}
				<!-- <section id="banner">
		
				</section> -->





			<!-- Footer -->
				<div id="footer">
					<div class="container">

				
						<div class="row">
							<div class="col-12">

								<!-- Contact -->
									<section class="contact">
										<header>
											<h3>Nisl turpis nascetur interdum?</h3>
										</header>
										<p>Urna nisl non quis interdum mus ornare ridiculus egestas ridiculus lobortis vivamus tempor aliquet.</p>
										<ul class="icons">
											<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
											<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
											<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
											<li><a href="#" class="icon brands fa-pinterest"><span class="label">Pinterest</span></a></li>
											<li><a href="#" class="icon brands fa-dribbble"><span class="label">Dribbble</span></a></li>
											<li><a href="#" class="icon brands fa-linkedin-in"><span class="label">Linkedin</span></a></li>
										</ul>
									</section>

								<!-- Copyright -->
									<div class="copyright">
										<ul class="menu">
											<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
										</ul>
									</div>

							</div>

						</div>
					</div>
				</div>

		</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.dropotron.min.js"></script>
			<script src="assets/js/jquery.scrolly.min.js"></script>
			<script src="assets/js/jquery.scrollex.min.js"></script>
			<script src="assets/js/browser.min.js"></script>
			<script src="assets/js/breakpoints.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

	</body>
</html>

WebsiteApp/templates/shop.html
{% extends 'padre.html' %}

{% block contenidoQueCambia %}

    <diV class="contenido">
        <h1 class="titulo">Shop</h1>

    </diV>

   
{% endblock contenidoQueCambia %}